language: go

# Test on 1.2 and 1.3, our supported versions
go:
  - 1.2
  - 1.3

# https://github.com/travis-ci/travis-ci/issues/2220
# Tests require ruby
install:
  - rvm get stable
  - rvm use 1.9.3 --install --binary --fuzzy

# Make will compile, download bundles and run tests
script:
  - make test
